<footer>
    <div class="footer-content">
        <div class="footer-logo">
            <h1>SwinCloud</h1>
            <p>Empowering Businesses with Cloud Computing</p>
        </div>
        <div class="footer-sections">
            <div class="footer-links footer-section">
                <h3>Quick Links</h3>
                <ul>
                    <li><a href="about.php">About us</a></li>
                    <li><a href="jobs.php">Jobs</a></li>
                    <li><a href="apply.php">Apply</a></li>
                </ul>
            </div>
            <div class="footer-contact footer-section">
                <h3>Contact Us</h3>
                <p>123 Cloud Street, Cloudville</p>
                <p>Email: info@swincloud.com</p>
                <p>Phone: +1 123 456 7890</p>
            </div>
        </div>
    </div>
    <div class="footer-bottom">
        <p>&copy; 2024 SwinCloud. All rights reserved.<br>Our video: https://www.youtube.com/watch?v=_zWMkrWsB8Q</p>
    </div>
</footer>