<nav class="navbar">
    <div class="container">
        <div class="logo">
            <a href="index.php">SwinCloud</a>
        </div>
        <div class="menu">
            <ul>
                <li><a href="about.php">About us</a></li>
                <li><a href="jobs.php">Jobs</a></li>
                <li><a href="apply.php">Apply</a></li>
                <li><a href="manage.php">EOI Management</a></li>
                <li><a href="phpenhancements.php">Job Management</a></li>
            </ul>
        </div>
    </div>
</nav>